name: Infra AKS

on:
  push:
    branches: [ "main" ]
    paths:
      - "**/*.tf"
      - ".github/workflows/infra-aks.yml"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  ARM_USE_OIDC: "true"
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  TF_IN_AUTOMATION: "true"

jobs:
  plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: azure

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-id: ${{ secrets.AZURE_CLIENT_ID }}

      - name: Set up OpenTofu
        uses: opentofu/setup-opentofu@v1

      - name: Init
        run: tofu init -upgrade

      - name: Plan
        run: tofu plan -out=plan.tfplan -input=false -compact-warnings

      - name: Upload plan artifact
        uses: actions/upload-artifact@v4
        with:
          name: plan-${{ github.sha }}
          path: azure/plan.tfplan
          retention-days: 7

  apply:
    runs-on: ubuntu-latest
    needs: plan
    environment: production   # 🔑 requires manual approval before running
    defaults:
      run:
        shell: bash
        working-directory: azure

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-id: ${{ secrets.AZURE_CLIENT_ID }}

      - name: Set up OpenTofu
        uses: opentofu/setup-opentofu@v1

      - name: Init
        run: tofu init -upgrade

      - name: Download plan artifact
        uses: actions/download-artifact@v4
        with:
          name: plan-${{ github.sha }}
          path: azure

      - name: Apply
        run: tofu apply -auto-approve -input=false plan.tfplan
