name: PR Plan

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "**/*.tf"
      - "**/*.tfvars"
      - ".github/workflows/pr-plan.yml"

permissions:
  id-token: write           # OIDC for Azure
  contents: read
  pull-requests: write      # so we can comment

env:
  ARM_USE_OIDC: "true"
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  TF_IN_AUTOMATION: "true"

jobs:
  plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./azure   # adjust if your .tf files move

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-id: ${{ secrets.AZURE_CLIENT_ID }}

      - name: Set up OpenTofu
        uses: opentofu/setup-opentofu@v1

      - name: Init
        run: tofu init -upgrade

      - name: Validate
        run: |
          tofu fmt -check -recursive
          tofu validate

      - name: Plan (create saved plan + diff summary)
        id: plan
        run: |
          set -e
          tofu plan -refresh=true -out=plan.tfplan -input=false -compact-warnings
          # Parse changes into diff-like output
          tofu show -json plan.tfplan | jq -r '
            .resource_changes
            | map(select(.change.actions != []))
            | map({addr: .address, act: ( .change.actions | join("/") )})
            | .[]
            | "\(.act) \(.addr)"
          ' > changes.txt || true

          {
            echo "### OpenTofu Plan Preview"
            echo
            if [ -s changes.txt ]; then
              echo "\`\`\`diff"
              while read -r line; do
                case "$line" in
                  create*) echo "+ $line" ;;
                  update*) echo "~ $line" ;;
                  delete*) echo "- $line" ;;
                  *) echo "  $line" ;;
                esac
              done < changes.txt
              echo "\`\`\`"
            else
              echo "✅ No changes"
            fi
          } > ../pr_comment.md

      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const body = fs.readFileSync('pr_comment.md', 'utf8');
            const {owner, repo, number} = context.issue;
            const comments = await github.rest.issues.listComments({owner, repo, issue_number: number});
            const mine = comments.data.find(c => c.user.type === 'Bot' && c.body && c.body.includes('OpenTofu Plan Preview'));
            if (mine) {
              await github.rest.issues.updateComment({owner, repo, comment_id: mine.id, body});
            } else {
              await github.rest.issues.createComment({owner, repo, issue_number: number, body});
            }

      - name: Upload plan artifact
        uses: actions/upload-artifact@v4
        with:
          name: plan-${{ github.event.pull_request.number }}
          path: |
            azure/plan.tfplan
          retention-days: 14
